PRINT_END

;; Start Cura Print Profile Settings
;; Generated: {date} {time}


;; Quality
; Infill Line Width:                            infill_line_width = {infill_line_width}
; Initial Layer Height:                         layer_height_0 = {layer_height_0}
; Initial Layer Line Width:                     initial_layer_line_width_factor = {initial_layer_line_width_factor}
; Inner Wall(s) Line Width:                     wall_line_width_x = {wall_line_width_x}
; Layer Height:                                 layer_height = {layer_height}
; Line Width:                                   line_width = {line_width}
; Outer Wall Line Width:                        wall_line_width_0 = {wall_line_width_0}
; Prime Tower Line Width:                       prime_tower_line_width = {prime_tower_line_width}
; Skirt/Brim Line Width:                        skirt_brim_line_width = {skirt_brim_line_width}
; Support Floor Line Width:                     support_bottom_line_width = {support_bottom_line_width}
; Support Interface Line Width:                 support_interface_line_width = {support_interface_line_width}
; Support Line Width:                           support_line_width = {support_line_width}
; Support Roof Line Width:                      support_roof_line_width = {support_roof_line_width}
; Top/Bottom Line Width:                        skin_line_width = {skin_line_width}
; Wall Line Width:                              wall_line_width = {wall_line_width}

;; Walls
; Alternate Extra Wall:                         alternate_extra_perimeter = {alternate_extra_perimeter}
; Compensate Inner Wall Overlaps:               travel_compensate_overlapping_walls_x_enabled = {travel_compensate_overlapping_walls_x_enabled}
; Compensate Outer Wall Overlaps:               travel_compensate_overlapping_walls_0_enabled = {travel_compensate_overlapping_walls_0_enabled}
; Compensate Wall Overlaps:                     travel_compensate_overlapping_walls_enabled = {travel_compensate_overlapping_walls_enabled}
; Fill Gaps Between Walls:                      fill_perimeter_gaps = {fill_perimeter_gaps}
; Filter Out Tiny Gaps:                         filter_out_tiny_gaps = {filter_out_tiny_gaps}
; Hole Horizontal Expansion:                    hole_xy_offset = {hole_xy_offset}
; Horizontal Expansion:                         xy_offset = {xy_offset}
; Initial Layer Horizontal Expansion:           xy_offset_layer_0 = {xy_offset_layer_0}
; Inner Wall Extruder:                          wall_x_extruder_nr = {wall_x_extruder_nr}
; Minimum Wall Flow:                            wall_min_flow = {wall_min_flow}
; Optimize Wall Printing Order:                 optimize_wall_printing_order = {optimize_wall_printing_order}
; Outer Before Inner Walls:                     outer_inset_first = {outer_inset_first}
; Outer Wall Extruder:                          wall_0_extruder_nr = {wall_0_extruder_nr}
; Outer Wall Inset:                             wall_0_inset = {wall_0_inset}
; Outer Wall Wipe Distance:                     wall_0_wipe_dist = {wall_0_wipe_dist}
; Prefer Retract:                               wall_min_flow_retract = {wall_min_flow_retract}
; Print Thin Walls:                             fill_outline_gaps = {fill_outline_gaps}
; Seam Corner Preference:                       z_seam_corner = {z_seam_corner}
; Wall Extruder:                                wall_extruder_nr = {wall_extruder_nr}
; Wall Line Count:                              wall_line_count = {wall_line_count}
; Wall Thickness:                               wall_thickness = {wall_thickness}
; Z Seam Alignment:                             z_seam_type = {z_seam_type}
; Z Seam Position:                              z_seam_position = {z_seam_position}
; Z Seam Relative:                              z_seam_relative = {z_seam_relative}
; Z Seam X:                                     z_seam_x = {z_seam_x}
; Z Seam Y:                                     z_seam_y = {z_seam_y}

;; Top/Bottom
; Bottom Layers:                                bottom_layers = {bottom_layers}
; Bottom Pattern Initial Layer:                 top_bottom_pattern_0 = {top_bottom_pattern_0}
; Bottom Skin Expand Distance:                  bottom_skin_expand_distance = {bottom_skin_expand_distance}
; Bottom Skin Removal Width:                    bottom_skin_preshrink = {bottom_skin_preshrink}
; Bottom Thickness:                             bottom_thickness = {bottom_thickness}
; Connect Top/Bottom Polygons:                  connect_skin_polygons = {connect_skin_polygons}
; Enable Ironing:                               ironing_enabled = {ironing_enabled}
; Extra Skin Wall Count:                        skin_outline_count = {skin_outline_count}
; Initial Bottom Layers:                        initial_bottom_layers = {initial_bottom_layers}
; Iron Only Highest Layer:                      ironing_only_highest_layer = {ironing_only_highest_layer}
; Ironing Acceleration:                         acceleration_ironing = {acceleration_ironing}
; Ironing Flow:                                 ironing_flow = {ironing_flow}
; Ironing Inset:                                ironing_inset = {ironing_inset}
; Ironing Jerk:                                 jerk_ironing = {jerk_ironing}
; Ironing Line Spacing:                         ironing_line_spacing = {ironing_line_spacing}
; Ironing Pattern:                              ironing_pattern = {ironing_pattern}
; Ironing Speed:                                speed_ironing = {speed_ironing}
; Maximum Skin Angle for Expansion:             max_skin_angle_for_expansion = {max_skin_angle_for_expansion}
; Minimum Skin Width for Expansion:             min_skin_width_for_expansion = {min_skin_width_for_expansion}
; No Skin in Z Gaps:                            skin_no_small_gaps_heuristic = {skin_no_small_gaps_heuristic}
; Skin Expand Distance:                         expand_skins_expand_distance = {expand_skins_expand_distance}
; Skin Overlap Percentage:                      skin_overlap = {skin_overlap}
; Skin Overlap:                                 skin_overlap_mm = {skin_overlap_mm}
; Skin Removal Width:                           skin_preshrink = {skin_preshrink}
; Top Layers:                                   top_layers = {top_layers}
; Top Skin Expand Distance:                     top_skin_expand_distance = {top_skin_expand_distance}
; Top Skin Removal Width:                       top_skin_preshrink = {top_skin_preshrink}
; Top Surface Skin Extruder:                    roofing_extruder_nr = {roofing_extruder_nr}
; Top Surface Skin Layers:                      roofing_layer_count = {roofing_layer_count}
; Top Thickness:                                top_thickness = {top_thickness}
; Top/Bottom Extruder:                          top_bottom_extruder_nr = {top_bottom_extruder_nr}
; Top/Bottom Line Directions:                   skin_angles = {skin_angles}
; Top/Bottom Pattern:                           top_bottom_pattern = {top_bottom_pattern}
; Top/Bottom Thickness:                         top_bottom_thickness = {top_bottom_thickness}

;; Infill
; Connect Infill Lines:                         zig_zaggify_infill = {zig_zaggify_infill}
; Connect Infill Polygons:                      connect_infill_polygons = {connect_infill_polygons}
; Cubic Subdivision Shell:                      sub_div_rad_add = {sub_div_rad_add}
; Extra Infill Wall Count:                      infill_wall_line_count = {infill_wall_line_count}
; Gradual Infill Step Height:                   gradual_infill_step_height = {gradual_infill_step_height}
; Gradual Infill Steps:                         gradual_infill_steps = {gradual_infill_steps}
; Infill Before Walls:                          infill_before_walls = {infill_before_walls}
; Infill Density:                               infill_sparse_density = {infill_sparse_density}
; Infill Extruder:                              infill_extruder_nr = {infill_extruder_nr}
; Infill Layer Thickness:                       infill_sparse_thickness = {infill_sparse_thickness}
; Infill Line Directions:                       infill_angles = {infill_angles}
; Infill Line Distance:                         infill_line_distance = {infill_line_distance}
; Infill Line Multiplier:                       infill_multiplier = {infill_multiplier}
; Infill Overhang Angle:                        infill_support_angle = {infill_support_angle}
; Infill Overlap Percentage:                    infill_overlap = {infill_overlap}
; Infill Overlap:                               infill_overlap_mm = {infill_overlap_mm}
; Infill Pattern:                               infill_pattern = {infill_pattern}
; Infill Support:                               infill_support_enabled = {infill_support_enabled}
; Infill Wipe Distance:                         infill_wipe_dist = {infill_wipe_dist}
; Infill X Offset:                              infill_offset_x = {infill_offset_x}
; Infill Y Offset:                              infill_offset_y = {infill_offset_y}
; Minimum Infill Area:                          min_infill_area = {min_infill_area}
; Randomize Infill Start:                       infill_randomize_start_location = {infill_randomize_start_location}
; Skin Edge Support Layers:                     skin_edge_support_layers = {skin_edge_support_layers}
; Skin Edge Support Thickness:                  skin_edge_support_thickness = {skin_edge_support_thickness}

;; Material
; Adhesion Tendency:                            material_adhesion_tendency = {material_adhesion_tendency}
; Anti-ooze Retracted Position:                 material_anti_ooze_retracted_position = {material_anti_ooze_retracted_position}
; Anti-ooze Retraction Speed:                   material_anti_ooze_retraction_speed = {material_anti_ooze_retraction_speed}
; Break Preparation Retracted Position:         material_break_preparation_retracted_position = {material_break_preparation_retracted_position}
; Break Preparation Retraction Speed:           material_break_preparation_speed = {material_break_preparation_speed}
; Break Preparation Temperature:                material_break_preparation_temperature = {material_break_preparation_temperature}
; Break Retracted Position:                     material_break_retracted_position = {material_break_retracted_position}
; Break Retraction Speed:                       material_break_speed = {material_break_speed}
; Break Temperature:                            material_break_temperature = {material_break_temperature}
; Build Plate Temperature Initial Layer:        material_bed_temperature_layer_0 = {material_bed_temperature_layer_0}
; Build Plate Temperature:                      material_bed_temperature = {material_bed_temperature}
; Build Volume Temperature:                     build_volume_temperature = {build_volume_temperature}
; Crystalline Material:                         material_crystallinity = {material_crystallinity}
; Default Build Plate Temperature:              default_material_bed_temperature = {default_material_bed_temperature}
; Default Printing Temperature:                 default_material_print_temperature = {default_material_print_temperature}
; End of Filament Purge Length:                 material_end_of_filament_purge_length = {material_end_of_filament_purge_length}
; End of Filament Purge Speed:                  material_end_of_filament_purge_speed = {material_end_of_filament_purge_speed}
; Extrusion Cool Down Speed Modifier:           material_extrusion_cool_down_speed = {material_extrusion_cool_down_speed}
; Final Printing Temperature:                   material_final_print_temperature = {material_final_print_temperature}
; Flow:                                         material_flow = {material_flow}
; Flush Purge Length:                           material_flush_purge_length = {material_flush_purge_length}
; Flush Purge Speed:                            material_flush_purge_speed = {material_flush_purge_speed}
; Infill Flow:                                  infill_material_flow = {infill_material_flow}
; Initial Layer Flow:                           material_flow_layer_0 = {material_flow_layer_0}
; Initial Printing Temperature:                 material_initial_print_temperature = {material_initial_print_temperature}
; Inner Wall(s) Flow:                           wall_x_material_flow = {wall_x_material_flow}
; Maximum Park Duration:                        material_maximum_park_duration = {material_maximum_park_duration}
; No Load Move Factor:                          material_no_load_move_factor = {material_no_load_move_factor}
; Outer Wall Flow:                              wall_0_material_flow = {wall_0_material_flow}
; Prime Tower Flow:                             prime_tower_flow = {prime_tower_flow}
; Printing Temperature Initial Layer:           material_print_temperature_layer_0 = {material_print_temperature_layer_0}
; Printing Temperature:                         material_print_temperature = {material_print_temperature}
; Scaling Factor Shrinkage Compensation:        material_shrinkage_percentage = {material_shrinkage_percentage}
; Skirt/Brim Flow:                              skirt_brim_material_flow = {skirt_brim_material_flow}
; Standby Temperature:                          material_standby_temperature = {material_standby_temperature}
; Support Floor Flow:                           support_bottom_material_flow = {support_bottom_material_flow}
; Support Flow:                                 support_material_flow = {support_material_flow}
; Support Interface Flow:                       support_interface_material_flow = {support_interface_material_flow}
; Support Roof Flow:                            support_roof_material_flow = {support_roof_material_flow}
; Surface Energy:                               material_surface_energy = {material_surface_energy}
; Top Surface Skin Flow:                        roofing_material_flow = {roofing_material_flow}
; Top/Bottom Flow:                              skin_material_flow = {skin_material_flow}
; Wall Flow:                                    wall_material_flow = {wall_material_flow}

;; Speed
; Enable Acceleration Control:                  acceleration_enabled = {acceleration_enabled}
; Enable Jerk Control:                          jerk_enabled = {jerk_enabled}
; Equalize Filament Flow:                       speed_equalize_flow_enabled = {speed_equalize_flow_enabled}
; Infill Acceleration:                          acceleration_infill = {acceleration_infill}
; Infill Jerk:                                  jerk_infill = {jerk_infill}
; Infill Speed:                                 speed_infill = {speed_infill}
; Initial Layer Acceleration:                   acceleration_layer_0 = {acceleration_layer_0}
; Initial Layer Jerk:                           jerk_layer_0 = {jerk_layer_0}
; Initial Layer Print Acceleration:             acceleration_print_layer_0 = {acceleration_print_layer_0}
; Initial Layer Print Jerk:                     jerk_print_layer_0 = {jerk_print_layer_0}
; Initial Layer Print Speed:                    speed_print_layer_0 = {speed_print_layer_0}
; Initial Layer Speed:                          speed_layer_0 = {speed_layer_0}
; Initial Layer Travel Acceleration:            acceleration_travel_layer_0 = {acceleration_travel_layer_0}
; Initial Layer Travel Jerk:                    jerk_travel_layer_0 = {jerk_travel_layer_0}
; Initial Layer Travel Speed:                   speed_travel_layer_0 = {speed_travel_layer_0}
; Inner Wall Acceleration:                      acceleration_wall_x = {acceleration_wall_x}
; Inner Wall Jerk:                              jerk_wall_x = {jerk_wall_x}
; Inner Wall Speed:                             speed_wall_x = {speed_wall_x}
; Maximum Speed for Flow Equalization:          speed_equalize_flow_max = {speed_equalize_flow_max}
; Number of Slower Layers:                      speed_slowdown_layers = {speed_slowdown_layers}
; Outer Wall Acceleration:                      acceleration_wall_0 = {acceleration_wall_0}
; Outer Wall Jerk:                              jerk_wall_0 = {jerk_wall_0}
; Outer Wall Speed:                             speed_wall_0 = {speed_wall_0}
; Prime Tower Acceleration:                     acceleration_prime_tower = {acceleration_prime_tower}
; Prime Tower Jerk:                             jerk_prime_tower = {jerk_prime_tower}
; Prime Tower Speed:                            speed_prime_tower = {speed_prime_tower}
; Print Acceleration:                           acceleration_print = {acceleration_print}
; Print Jerk:                                   jerk_print = {jerk_print}
; Print Speed:                                  speed_print = {speed_print}
; Skirt/Brim Acceleration:                      acceleration_skirt_brim = {acceleration_skirt_brim}
; Skirt/Brim Jerk:                              jerk_skirt_brim = {jerk_skirt_brim}
; Skirt/Brim Speed:                             skirt_brim_speed = {skirt_brim_speed}
; Support Acceleration:                         acceleration_support = {acceleration_support}
; Support Floor Acceleration:                   acceleration_support_bottom = {acceleration_support_bottom}
; Support Floor Jerk:                           jerk_support_bottom = {jerk_support_bottom}
; Support Floor Speed:                          speed_support_bottom = {speed_support_bottom}
; Support Infill Acceleration:                  acceleration_support_infill = {acceleration_support_infill}
; Support Infill Jerk:                          jerk_support_infill = {jerk_support_infill}
; Support Infill Speed:                         speed_support_infill = {speed_support_infill}
; Support Interface Acceleration:               acceleration_support_interface = {acceleration_support_interface}
; Support Interface Jerk:                       jerk_support_interface = {jerk_support_interface}
; Support Interface Speed:                      speed_support_interface = {speed_support_interface}
; Support Jerk:                                 jerk_support = {jerk_support}
; Support Roof Acceleration:                    acceleration_support_roof = {acceleration_support_roof}
; Support Roof Jerk:                            jerk_support_roof = {jerk_support_roof}
; Support Roof Speed:                           speed_support_roof = {speed_support_roof}
; Support Speed:                                speed_support = {speed_support}
; Top Surface Skin Acceleration:                acceleration_roofing = {acceleration_roofing}
; Top Surface Skin Jerk:                        jerk_roofing = {jerk_roofing}
; Top Surface Skin Speed:                       speed_roofing = {speed_roofing}
; Top/Bottom Acceleration:                      acceleration_topbottom = {acceleration_topbottom}
; Top/Bottom Jerk:                              jerk_topbottom = {jerk_topbottom}
; Top/Bottom Speed:                             speed_topbottom = {speed_topbottom}
; Travel Acceleration:                          acceleration_travel = {acceleration_travel}
; Travel Jerk:                                  jerk_travel = {jerk_travel}
; Travel Speed:                                 speed_travel = {speed_travel}
; Wall Acceleration:                            acceleration_wall = {acceleration_wall}
; Wall Jerk:                                    jerk_wall = {jerk_wall}
; Wall Speed:                                   speed_wall = {speed_wall}
; Z Hop Speed:                                  speed_z_hop = {speed_z_hop}

;; Travel
; Avoid Printed Parts When Traveling:           travel_avoid_other_parts = {travel_avoid_other_parts}
; Avoid Supports When Traveling:                travel_avoid_supports = {travel_avoid_supports}
; Combing Mode:                                 retraction_combing = {retraction_combing}
; Enable Retraction:                            retraction_enable = {retraction_enable}
; Layer Start X:                                layer_start_x = {layer_start_x}
; Layer Start Y:                                layer_start_y = {layer_start_y}
; Limit Support Retractions:                    limit_support_retractions = {limit_support_retractions}
; Max Comb Distance With No Retract:            retraction_combing_max_distance = {retraction_combing_max_distance}
; Maximum Retraction Count:                     retraction_count_max = {retraction_count_max}
; Minimum Extrusion Distance Window:            retraction_extrusion_window = {retraction_extrusion_window}
; Retract Before Outer Wall:                    travel_retract_before_outer_wall = {travel_retract_before_outer_wall}
; Retract at Layer Change:                      retract_at_layer_change = {retract_at_layer_change}
; Retraction Distance:                          retraction_amount = {retraction_amount}
; Retraction Extra Prime Amount:                retraction_extra_prime_amount = {retraction_extra_prime_amount}
; Retraction Minimum Travel:                    retraction_min_travel = {retraction_min_travel}
; Retraction Prime Speed:                       retraction_prime_speed = {retraction_prime_speed}
; Retraction Retract Speed:                     retraction_retract_speed = {retraction_retract_speed}
; Retraction Speed:                             retraction_speed = {retraction_speed}
; Travel Avoid Distance:                        travel_avoid_distance = {travel_avoid_distance}
; Z Hop After Extruder Switch Height:           retraction_hop_after_extruder_switch_height = {retraction_hop_after_extruder_switch_height}
; Z Hop After Extruder Switch:                  retraction_hop_after_extruder_switch = {retraction_hop_after_extruder_switch}
; Z Hop Height:                                 retraction_hop = {retraction_hop}
; Z Hop Only Over Printed Parts:                retraction_hop_only_when_collides = {retraction_hop_only_when_collides}
; Z Hop When Retracted:                         retraction_hop_enabled = {retraction_hop_enabled}

;; Cooling
; Enable Print Cooling:                         cool_fan_enabled = {cool_fan_enabled}
; Fan Speed:                                    cool_fan_speed = {cool_fan_speed}
; Initial Fan Speed:                            cool_fan_speed_0 = {cool_fan_speed_0}
; Lift Head:                                    cool_lift_head = {cool_lift_head}
; Maximum Fan Speed:                            cool_fan_speed_max = {cool_fan_speed_max}
; Minimum Layer Time:                           cool_min_layer_time = {cool_min_layer_time}
; Minimum Speed:                                cool_min_speed = {cool_min_speed}
; Regular Fan Speed at Height:                  cool_fan_full_at_height = {cool_fan_full_at_height}
; Regular Fan Speed at Layer:                   cool_fan_full_layer = {cool_fan_full_layer}
; Regular Fan Speed:                            cool_fan_speed_min = {cool_fan_speed_min}
; Regular/Maximum Fan Speed Threshold:          cool_min_layer_time_fan_speed_max = {cool_min_layer_time_fan_speed_max}

;; Support
; Connect Support Lines:                        zig_zaggify_support = {zig_zaggify_support}
; Connect Support ZigZags:                      support_connect_zigzags = {support_connect_zigzags}
; Drop Down Support Mesh:                       support_mesh_drop_down = {support_mesh_drop_down}
; Enable Support Brim:                          support_brim_enable = {support_brim_enable}
; Enable Support Floor:                         support_bottom_enable = {support_bottom_enable}
; Enable Support Interface:                     support_interface_enable = {support_interface_enable}
; Enable Support Roof:                          support_roof_enable = {support_roof_enable}
; Fan Speed Override:                           support_fan_enable = {support_fan_enable}
; First Layer Support Extruder:                 support_extruder_nr_layer_0 = {support_extruder_nr_layer_0}
; Generate Support:                             support_enable = {support_enable}
; Gradual Support Infill Step Height:           gradual_support_infill_step_height = {gradual_support_infill_step_height}
; Gradual Support Infill Steps:                 gradual_support_infill_steps = {gradual_support_infill_steps}
; Initial Layer Support Line Distance:          support_initial_layer_line_distance = {support_initial_layer_line_distance}
; Maximum Tower-Supported Diameter:             support_tower_maximum_supported_diameter = {support_tower_maximum_supported_diameter}
; Minimum Support Area:                         minimum_support_area = {minimum_support_area}
; Minimum Support Floor Area:                   minimum_bottom_area = {minimum_bottom_area}
; Minimum Support Interface Area:               minimum_interface_area = {minimum_interface_area}
; Minimum Support Roof Area:                    minimum_roof_area = {minimum_roof_area}
; Minimum Support X/Y Distance:                 support_xy_distance_overhang = {support_xy_distance_overhang}
; Scene Has Support Meshes:                     support_meshes_present = {support_meshes_present}
; Support Bottom Distance:                      support_bottom_distance = {support_bottom_distance}
; Support Brim Line Count:                      support_brim_line_count = {support_brim_line_count}
; Support Brim Width:                           support_brim_width = {support_brim_width}
; Support Density:                              support_infill_rate = {support_infill_rate}
; Support Distance Priority:                    support_xy_overrides_z = {support_xy_overrides_z}
; Support Extruder:                             support_extruder_nr = {support_extruder_nr}
; Support Floor Density:                        support_bottom_density = {support_bottom_density}
; Support Floor Extruder:                       support_bottom_extruder_nr = {support_bottom_extruder_nr}
; Support Floor Horizontal Expansion:           support_bottom_offset = {support_bottom_offset}
; Support Floor Line Directions:                support_bottom_angles = {support_bottom_angles}
; Support Floor Line Distance:                  support_bottom_line_distance = {support_bottom_line_distance}
; Support Floor Pattern:                        support_bottom_pattern = {support_bottom_pattern}
; Support Floor Thickness:                      support_bottom_height = {support_bottom_height}
; Support Horizontal Expansion:                 support_offset = {support_offset}
; Support Infill Extruder:                      support_infill_extruder_nr = {support_infill_extruder_nr}
; Support Infill Layer Thickness:               support_infill_sparse_thickness = {support_infill_sparse_thickness}
; Support Infill Line Directions:               support_infill_angles = {support_infill_angles}
; Support Interface Density:                    support_interface_density = {support_interface_density}
; Support Interface Extruder:                   support_interface_extruder_nr = {support_interface_extruder_nr}
; Support Interface Horizontal Expansion:       support_interface_offset = {support_interface_offset}
; Support Interface Line Directions:            support_interface_angles = {support_interface_angles}
; Support Interface Pattern:                    support_interface_pattern = {support_interface_pattern}
; Support Interface Resolution:                 support_interface_skip_height = {support_interface_skip_height}
; Support Interface Thickness:                  support_interface_height = {support_interface_height}
; Support Join Distance:                        support_join_distance = {support_join_distance}
; Support Line Distance:                        support_line_distance = {support_line_distance}
; Support Overhang Angle:                       support_angle = {support_angle}
; Support Pattern:                              support_pattern = {support_pattern}
; Support Placement:                            support_type = {support_type}
; Support Roof Density:                         support_roof_density = {support_roof_density}
; Support Roof Extruder:                        support_roof_extruder_nr = {support_roof_extruder_nr}
; Support Roof Horizontal Expansion:            support_roof_offset = {support_roof_offset}
; Support Roof Line Directions:                 support_roof_angles = {support_roof_angles}
; Support Roof Line Distance:                   support_roof_line_distance = {support_roof_line_distance}
; Support Roof Pattern:                         support_roof_pattern = {support_roof_pattern}
; Support Roof Thickness:                       support_roof_height = {support_roof_height}
; Support Stair Step Height:                    support_bottom_stair_step_height = {support_bottom_stair_step_height}
; Support Stair Step Maximum Width:             support_bottom_stair_step_width = {support_bottom_stair_step_width}
; Support Stair Step Minimum Slope Angle:       support_bottom_stair_step_min_slope = {support_bottom_stair_step_min_slope}
; Support Structure:                            support_structure = {support_structure}
; Support Top Distance:                         support_top_distance = {support_top_distance}
; Support Wall Line Count:                      support_wall_count = {support_wall_count}
; Support X/Y Distance:                         support_xy_distance = {support_xy_distance}
; Support Z Distance:                           support_z_distance = {support_z_distance}
; Supported Skin Fan Speed:                     support_supported_skin_fan_speed = {support_supported_skin_fan_speed}
; Tower Diameter:                               support_tower_diameter = {support_tower_diameter}
; Tower Roof Angle:                             support_tower_roof_angle = {support_tower_roof_angle}
; Tree Support Branch Angle:                    support_tree_angle = {support_tree_angle}
; Tree Support Branch Diameter Angle:           support_tree_branch_diameter_angle = {support_tree_branch_diameter_angle}
; Tree Support Branch Diameter:                 support_tree_branch_diameter = {support_tree_branch_diameter}
; Tree Support Branch Distance:                 support_tree_branch_distance = {support_tree_branch_distance}
; Tree Support Collision Resolution:            support_tree_collision_resolution = {support_tree_collision_resolution}
; Use Towers:                                   support_use_towers = {support_use_towers}

;; Build Plate Adhesion
; Brim Distance:                                brim_gap = {brim_gap}
; Brim Line Count:                              brim_line_count = {brim_line_count}
; Brim Only on Outside:                         brim_outside_only = {brim_outside_only}
; Brim Replaces Support:                        brim_replaces_support = {brim_replaces_support}
; Brim Width:                                   brim_width = {brim_width}
; Build Plate Adhesion Extruder:                adhesion_extruder_nr = {adhesion_extruder_nr}
; Build Plate Adhesion Type:                    adhesion_type = {adhesion_type}
; Enable Prime Blob:                            prime_blob_enable = {prime_blob_enable}
; Extruder Prime X Position:                    extruder_prime_pos_x = {extruder_prime_pos_x}
; Extruder Prime Y Position:                    extruder_prime_pos_y = {extruder_prime_pos_y}
; Initial Layer Z Overlap:                      layer_0_z_overlap = {layer_0_z_overlap}
; Raft Air Gap:                                 raft_airgap = {raft_airgap}
; Raft Base Fan Speed:                          raft_base_fan_speed = {raft_base_fan_speed}
; Raft Base Line Spacing:                       raft_base_line_spacing = {raft_base_line_spacing}
; Raft Base Line Width:                         raft_base_line_width = {raft_base_line_width}
; Raft Base Print Acceleration:                 raft_base_acceleration = {raft_base_acceleration}
; Raft Base Print Jerk:                         raft_base_jerk = {raft_base_jerk}
; Raft Base Print Speed:                        raft_base_speed = {raft_base_speed}
; Raft Base Thickness:                          raft_base_thickness = {raft_base_thickness}
; Raft Extra Margin:                            raft_margin = {raft_margin}
; Raft Fan Speed:                               raft_fan_speed = {raft_fan_speed}
; Raft Middle Fan Speed:                        raft_interface_fan_speed = {raft_interface_fan_speed}
; Raft Middle Line Width:                       raft_interface_line_width = {raft_interface_line_width}
; Raft Middle Print Acceleration:               raft_interface_acceleration = {raft_interface_acceleration}
; Raft Middle Print Jerk:                       raft_interface_jerk = {raft_interface_jerk}
; Raft Middle Print Speed:                      raft_interface_speed = {raft_interface_speed}
; Raft Middle Spacing:                          raft_interface_line_spacing = {raft_interface_line_spacing}
; Raft Middle Thickness:                        raft_interface_thickness = {raft_interface_thickness}
; Raft Print Acceleration:                      raft_acceleration = {raft_acceleration}
; Raft Print Jerk:                              raft_jerk = {raft_jerk}
; Raft Print Speed:                             raft_speed = {raft_speed}
; Raft Smoothing:                               raft_smoothing = {raft_smoothing}
; Raft Top Fan Speed:                           raft_surface_fan_speed = {raft_surface_fan_speed}
; Raft Top Layer Thickness:                     raft_surface_thickness = {raft_surface_thickness}
; Raft Top Layers:                              raft_surface_layers = {raft_surface_layers}
; Raft Top Line Width:                          raft_surface_line_width = {raft_surface_line_width}
; Raft Top Print Acceleration:                  raft_surface_acceleration = {raft_surface_acceleration}
; Raft Top Print Jerk:                          raft_surface_jerk = {raft_surface_jerk}
; Raft Top Print Speed:                         raft_surface_speed = {raft_surface_speed}
; Raft Top Spacing:                             raft_surface_line_spacing = {raft_surface_line_spacing}
; Skirt Distance:                               skirt_gap = {skirt_gap}
; Skirt Line Count:                             skirt_line_count = {skirt_line_count}
; Skirt/Brim Minimum Length:                    skirt_brim_minimal_length = {skirt_brim_minimal_length}

;; Dual Extrusion
; Enable Ooze Shield:                           ooze_shield_enabled = {ooze_shield_enabled}
; Enable Prime Tower:                           prime_tower_enable = {prime_tower_enable}
; Nozzle Switch Extra Prime Amount:             switch_extruder_extra_prime_amount = {switch_extruder_extra_prime_amount}
; Nozzle Switch Prime Speed:                    switch_extruder_prime_speed = {switch_extruder_prime_speed}
; Nozzle Switch Retract Speed:                  switch_extruder_retraction_speed = {switch_extruder_retraction_speed}
; Nozzle Switch Retraction Distance:            switch_extruder_retraction_amount = {switch_extruder_retraction_amount}
; Nozzle Switch Retraction Speed:               switch_extruder_retraction_speeds = {switch_extruder_retraction_speeds}
; Ooze Shield Angle:                            ooze_shield_angle = {ooze_shield_angle}
; Ooze Shield Distance:                         ooze_shield_dist = {ooze_shield_dist}
; Prime Tower Brim:                             prime_tower_brim_enable = {prime_tower_brim_enable}
; Prime Tower Minimum Volume:                   prime_tower_min_volume = {prime_tower_min_volume}
; Prime Tower Size:                             prime_tower_size = {prime_tower_size}
; Prime Tower X Position:                       prime_tower_position_x = {prime_tower_position_x}
; Prime Tower Y Position:                       prime_tower_position_y = {prime_tower_position_y}
; Wipe Inactive Nozzle on Prime Tower:          prime_tower_wipe_enabled = {prime_tower_wipe_enabled}

;; Mesh Fixes
; Alternate Mesh Removal:                       alternate_carve_order = {alternate_carve_order}
; Extensive Stitching:                          meshfix_extensive_stitching = {meshfix_extensive_stitching}
; Keep Disconnected Faces:                      meshfix_keep_open_polygons = {meshfix_keep_open_polygons}
; Maximum Deviation:                            meshfix_maximum_deviation = {meshfix_maximum_deviation}
; Maximum Resolution:                           meshfix_maximum_resolution = {meshfix_maximum_resolution}
; Maximum Travel Resolution:                    meshfix_maximum_travel_resolution = {meshfix_maximum_travel_resolution}
; Merged Meshes Overlap:                        multiple_mesh_overlap = {multiple_mesh_overlap}
; Remove All Holes:                             meshfix_union_all_remove_holes = {meshfix_union_all_remove_holes}
; Remove Empty First Layers:                    remove_empty_first_layers = {remove_empty_first_layers}
; Remove Mesh Intersection:                     carve_multiple_volumes = {carve_multiple_volumes}
; Union Overlapping Volumes:                    meshfix_union_all = {meshfix_union_all}

;; Special Modes
; Anti Overhang Mesh:                           anti_overhang_mesh = {anti_overhang_mesh}
; Cutting Mesh:                                 cutting_mesh = {cutting_mesh}
; Infill Mesh:                                  infill_mesh = {infill_mesh}
; Mesh Processing Rank:                         infill_mesh_order = {infill_mesh_order}
; Minimal Mold Width:                           mold_width = {mold_width}
; Mold Angle:                                   mold_angle = {mold_angle}
; Mold Roof Height:                             mold_roof_height = {mold_roof_height}
; Mold:                                         mold_enabled = {mold_enabled}
; Print Sequence:                               print_sequence = {print_sequence}
; Relative Extrusion:                           relative_extrusion = {relative_extrusion}
; Smooth Spiralized Contours:                   smooth_spiralized_contours = {smooth_spiralized_contours}
; Spiralize Outer Contour:                      magic_spiralize = {magic_spiralize}
; Support Mesh:                                 support_mesh = {support_mesh}
; Surface Mode:                                 magic_mesh_surface_mode = {magic_mesh_surface_mode}

;; Experimental
; Adaptive Layers Maximum Variation:            adaptive_layer_height_variation = {adaptive_layer_height_variation}
; Adaptive Layers Topography Size:              adaptive_layer_height_threshold = {adaptive_layer_height_threshold}
; Adaptive Layers Variation Step Size:          adaptive_layer_height_variation_step = {adaptive_layer_height_variation_step}
; Auto Temperature:                             material_flow_dependent_temperature = {material_flow_dependent_temperature}
; Break Up Support In Chunks:                   support_skip_some_zags = {support_skip_some_zags}
; Bridge Fan Speed:                             bridge_fan_speed = {bridge_fan_speed}
; Bridge Has Multiple Layers:                   bridge_enable_more_layers = {bridge_enable_more_layers}
; Bridge Second Skin Density:                   bridge_skin_density_2 = {bridge_skin_density_2}
; Bridge Second Skin Fan Speed:                 bridge_fan_speed_2 = {bridge_fan_speed_2}
; Bridge Second Skin Flow:                      bridge_skin_material_flow_2 = {bridge_skin_material_flow_2}
; Bridge Second Skin Speed:                     bridge_skin_speed_2 = {bridge_skin_speed_2}
; Bridge Skin Density:                          bridge_skin_density = {bridge_skin_density}
; Bridge Skin Flow:                             bridge_skin_material_flow = {bridge_skin_material_flow}
; Bridge Skin Speed:                            bridge_skin_speed = {bridge_skin_speed}
; Bridge Skin Support Threshold:                bridge_skin_support_threshold = {bridge_skin_support_threshold}
; Bridge Sparse Infill Max Density:             bridge_sparse_infill_max_density = {bridge_sparse_infill_max_density}
; Bridge Third Skin Density:                    bridge_skin_density_3 = {bridge_skin_density_3}
; Bridge Third Skin Fan Speed:                  bridge_fan_speed_3 = {bridge_fan_speed_3}
; Bridge Third Skin Flow:                       bridge_skin_material_flow_3 = {bridge_skin_material_flow_3}
; Bridge Third Skin Speed:                      bridge_skin_speed_3 = {bridge_skin_speed_3}
; Bridge Wall Coasting:                         bridge_wall_coast = {bridge_wall_coast}
; Bridge Wall Flow:                             bridge_wall_material_flow = {bridge_wall_material_flow}
; Bridge Wall Speed:                            bridge_wall_speed = {bridge_wall_speed}
; Coasting Speed:                               coasting_speed = {coasting_speed}
; Coasting Volume:                              coasting_volume = {coasting_volume}
; Conical Support Angle:                        support_conical_angle = {support_conical_angle}
; Conical Support Minimum Width:                support_conical_min_width = {support_conical_min_width}
; Cross 3D Pocket Size:                         cross_infill_pocket_size = {cross_infill_pocket_size}
; Cross Fill Density Image for Support:         cross_support_density_image = {cross_support_density_image}
; Cross Infill Density Image:                   cross_infill_density_image = {cross_infill_density_image}
; Draft Shield Height:                          draft_shield_height = {draft_shield_height}
; Draft Shield Limitation:                      draft_shield_height_limitation = {draft_shield_height_limitation}
; Draft Shield X/Y Distance:                    draft_shield_dist = {draft_shield_dist}
; Enable Bridge Settings:                       bridge_settings_enabled = {bridge_settings_enabled}
; Enable Coasting:                              coasting_enable = {coasting_enable}
; Enable Conical Support:                       support_conical_enabled = {support_conical_enabled}
; Enable Draft Shield:                          draft_shield_enabled = {draft_shield_enabled}
; Flow Rate Compensation Factor:                flow_rate_extrusion_offset_factor = {flow_rate_extrusion_offset_factor}
; Flow Rate Compensation Max Extrusion Offset:  flow_rate_max_extrusion_offset = {flow_rate_max_extrusion_offset}
; Flow Temperature Graph:                       material_flow_temp_graph = {material_flow_temp_graph}
; Fuzzy Skin Density:                           magic_fuzzy_skin_point_density = {magic_fuzzy_skin_point_density}
; Fuzzy Skin Outside Only:                      magic_fuzzy_skin_outside_only = {magic_fuzzy_skin_outside_only}
; Fuzzy Skin Point Distance:                    magic_fuzzy_skin_point_dist = {magic_fuzzy_skin_point_dist}
; Fuzzy Skin Thickness:                         magic_fuzzy_skin_thickness = {magic_fuzzy_skin_thickness}
; Fuzzy Skin:                                   magic_fuzzy_skin_enabled = {magic_fuzzy_skin_enabled}
; Infill Travel Optimization:                   infill_enable_travel_optimization = {infill_enable_travel_optimization}
; Make Overhang Printable:                      conical_overhang_enabled = {conical_overhang_enabled}
; Material Volume Between Wipes:                max_extrusion_before_wipe = {max_extrusion_before_wipe}
; Maximum Model Angle:                          conical_overhang_angle = {conical_overhang_angle}
; Maximum Overhang Hole Area:                   conical_overhang_hole_size = {conical_overhang_hole_size}
; Minimum Bridge Wall Length:                   bridge_wall_min_length = {bridge_wall_min_length}
; Minimum Polygon Circumference:                minimum_polygon_circumference = {minimum_polygon_circumference}
; Minimum Volume Before Coasting:               coasting_min_volume = {coasting_min_volume}
; Overhanging Wall Angle:                       wall_overhang_angle = {wall_overhang_angle}
; Overhanging Wall Speed:                       wall_overhang_speed_factor = {wall_overhang_speed_factor}
; Slicing Tolerance:                            slicing_tolerance = {slicing_tolerance}
; Small Feature Initial Layer Speed:            small_feature_speed_factor_0 = {small_feature_speed_factor_0}
; Small Feature Max Length:                     small_feature_max_length = {small_feature_max_length}
; Small Feature Speed:                          small_feature_speed_factor = {small_feature_speed_factor}
; Small Hole Max Size:                          small_hole_max_size = {small_hole_max_size}
; Support Chunk Line Count:                     support_zag_skip_count = {support_zag_skip_count}
; Support Chunk Size:                           support_skip_zag_per_mm = {support_skip_zag_per_mm}
; Top Surface Skin Line Directions:             roofing_angles = {roofing_angles}
; Top Surface Skin Line Width:                  roofing_line_width = {roofing_line_width}
; Top Surface Skin Pattern:                     roofing_pattern = {roofing_pattern}
; Use Adaptive Layers:                          adaptive_layer_height_enabled = {adaptive_layer_height_enabled}
; WP Bottom Delay:                              wireframe_bottom_delay = {wireframe_bottom_delay}
; WP Bottom Printing Speed:                     wireframe_printspeed_bottom = {wireframe_printspeed_bottom}
; WP Connection Flow:                           wireframe_flow_connection = {wireframe_flow_connection}
; WP Connection Height:                         wireframe_height = {wireframe_height}
; WP Downward Printing Speed:                   wireframe_printspeed_down = {wireframe_printspeed_down}
; WP Drag Along:                                wireframe_drag_along = {wireframe_drag_along}
; WP Ease Upward:                               wireframe_up_half_speed = {wireframe_up_half_speed}
; WP Fall Down:                                 wireframe_fall_down = {wireframe_fall_down}
; WP Flat Delay:                                wireframe_flat_delay = {wireframe_flat_delay}
; WP Flat Flow:                                 wireframe_flow_flat = {wireframe_flow_flat}
; WP Flow:                                      wireframe_flow = {wireframe_flow}
; WP Horizontal Printing Speed:                 wireframe_printspeed_flat = {wireframe_printspeed_flat}
; WP Knot Size:                                 wireframe_top_jump = {wireframe_top_jump}
; WP Nozzle Clearance:                          wireframe_nozzle_clearance = {wireframe_nozzle_clearance}
; WP Roof Drag Along:                           wireframe_roof_drag_along = {wireframe_roof_drag_along}
; WP Roof Fall Down:                            wireframe_roof_fall_down = {wireframe_roof_fall_down}
; WP Roof Inset Distance:                       wireframe_roof_inset = {wireframe_roof_inset}
; WP Roof Outer Delay:                          wireframe_roof_outer_delay = {wireframe_roof_outer_delay}
; WP Speed:                                     wireframe_printspeed = {wireframe_printspeed}
; WP Straighten Downward Lines:                 wireframe_straight_before_down = {wireframe_straight_before_down}
; WP Strategy:                                  wireframe_strategy = {wireframe_strategy}
; WP Top Delay:                                 wireframe_top_delay = {wireframe_top_delay}
; WP Upward Printing Speed:                     wireframe_printspeed_up = {wireframe_printspeed_up}
; Wipe Brush X Position:                        wipe_brush_pos_x = {wipe_brush_pos_x}
; Wipe Hop Speed:                               wipe_hop_speed = {wipe_hop_speed}
; Wipe Move Distance:                           wipe_move_distance = {wipe_move_distance}
; Wipe Nozzle Between Layers:                   clean_between_layers = {clean_between_layers}
; Wipe Pause:                                   wipe_pause = {wipe_pause}
; Wipe Repeat Count:                            wipe_repeat_count = {wipe_repeat_count}
; Wipe Retraction Distance:                     wipe_retraction_amount = {wipe_retraction_amount}
; Wipe Retraction Enable:                       wipe_retraction_enable = {wipe_retraction_enable}
; Wipe Retraction Extra Prime Amount:           wipe_retraction_extra_prime_amount = {wipe_retraction_extra_prime_amount}
; Wipe Retraction Prime Speed:                  wipe_retraction_prime_speed = {wipe_retraction_prime_speed}
; Wipe Retraction Retract Speed:                wipe_retraction_retract_speed = {wipe_retraction_retract_speed}
; Wipe Retraction Speed:                        wipe_retraction_speed = {wipe_retraction_speed}
; Wipe Z Hop Height:                            wipe_hop_amount = {wipe_hop_amount}
; Wipe Z Hop:                                   wipe_hop_enable = {wipe_hop_enable}
; Wire Printing:                                wireframe_enabled = {wireframe_enabled}

;; Machine
; Absolute Extruder Prime Position:             extruder_prime_pos_abs = {extruder_prime_pos_abs}
; Always Write Active Tool:                     machine_always_write_active_tool = {machine_always_write_active_tool}
; Build Plate Material:                         machine_buildplate_type = {machine_buildplate_type}
; Build Plate Shape:                            machine_shape = {machine_shape}
; Cool Down Speed:                              machine_nozzle_cool_down_speed = {machine_nozzle_cool_down_speed}
; Default Acceleration:                         machine_acceleration = {machine_acceleration}
; Default Filament Jerk:                        machine_max_jerk_e = {machine_max_jerk_e}
; Default X-Y Jerk:                             machine_max_jerk_xy = {machine_max_jerk_xy}
; Default Z Jerk:                               machine_max_jerk_z = {machine_max_jerk_z}
; Diameter:                                     material_diameter = {material_diameter}
; Disallowed Areas:                             machine_disallowed_areas = {machine_disallowed_areas}
; Enable Nozzle Temperature Control:            machine_nozzle_temp_enabled = {machine_nozzle_temp_enabled}
; Extruder Prime Z Position:                    extruder_prime_pos_z = {extruder_prime_pos_z}
; Extruders Share Heater:                       machine_extruders_share_heater = {machine_extruders_share_heater}
; Extruders Share Nozzle:                       machine_extruders_share_nozzle = {machine_extruders_share_nozzle}
; Feeder Wheel Diameter:                        machine_feeder_wheel_diameter = {machine_feeder_wheel_diameter}
; Firmware Retraction:                          machine_firmware_retract = {machine_firmware_retract}
; G-code Flavor:                                machine_gcode_flavor = {machine_gcode_flavor}
; Gantry Height:                                gantry_height = {gantry_height}
; Has Build Volume Temperature Stabilization:   machine_heated_build_volume = {machine_heated_build_volume}
; Has Heated Build Plate:                       machine_heated_bed = {machine_heated_bed}
; Heat Up Speed:                                machine_nozzle_heat_up_speed = {machine_nozzle_heat_up_speed}
; Heat Zone Length:                             machine_heat_zone_length = {machine_heat_zone_length}
; Include Build Plate Temperature:              material_bed_temp_prepend = {material_bed_temp_prepend}
; Include Material Temperatures:                material_print_temp_prepend = {material_print_temp_prepend}
; Is Center Origin:                             machine_center_is_zero = {machine_center_is_zero}
; Machine Depth:                                machine_depth = {machine_depth}
; Machine Head & Fan Polygon:                   machine_head_with_fans_polygon = {machine_head_with_fans_polygon}
; Machine Height:                               machine_height = {machine_height}
; Machine Type:                                 machine_name = {machine_name}
; Machine Width:                                machine_width = {machine_width}
; Material GUID:                                material_guid = {material_guid}
; Maximum Acceleration X:                       machine_max_acceleration_x = {machine_max_acceleration_x}
; Maximum Acceleration Y:                       machine_max_acceleration_y = {machine_max_acceleration_y}
; Maximum Acceleration Z:                       machine_max_acceleration_z = {machine_max_acceleration_z}
; Maximum Feedrate:                             machine_max_feedrate_e = {machine_max_feedrate_e}
; Maximum Filament Acceleration:                machine_max_acceleration_e = {machine_max_acceleration_e}
; Maximum Speed X:                              machine_max_feedrate_x = {machine_max_feedrate_x}
; Maximum Speed Y:                              machine_max_feedrate_y = {machine_max_feedrate_y}
; Maximum Speed Z:                              machine_max_feedrate_z = {machine_max_feedrate_z}
; Minimal Time Standby Temperature:             machine_min_cool_heat_time_window = {machine_min_cool_heat_time_window}
; Minimum Feedrate:                             machine_minimum_feedrate = {machine_minimum_feedrate}
; Nozzle Angle:                                 machine_nozzle_expansion_angle = {machine_nozzle_expansion_angle}
; Nozzle Diameter:                              machine_nozzle_size = {machine_nozzle_size}
; Nozzle Disallowed Areas:                      nozzle_disallowed_areas = {nozzle_disallowed_areas}
; Nozzle ID:                                    machine_nozzle_id = {machine_nozzle_id}
; Nozzle Length:                                machine_nozzle_head_distance = {machine_nozzle_head_distance}
; Number of Extruders That Are Enabled:         extruders_enabled_count = {extruders_enabled_count}
; Number of Extruders:                          machine_extruder_count = {machine_extruder_count}
; Offset with Extruder:                         machine_use_extruder_offset_to_offset_coords = {machine_use_extruder_offset_to_offset_coords}
; Outer Nozzle Diameter:                        machine_nozzle_tip_outer_diameter = {machine_nozzle_tip_outer_diameter}
; Shared Nozzle Initial Retraction:             machine_extruders_shared_nozzle_initial_retraction = {machine_extruders_shared_nozzle_initial_retraction}
; Show Machine Variants:                        machine_show_variants = {machine_show_variants}
; Steps per Millimeter (E):                     machine_steps_per_mm_e = {machine_steps_per_mm_e}
; Steps per Millimeter (X):                     machine_steps_per_mm_x = {machine_steps_per_mm_x}
; Steps per Millimeter (Y):                     machine_steps_per_mm_y = {machine_steps_per_mm_y}
; Steps per Millimeter (Z):                     machine_steps_per_mm_z = {machine_steps_per_mm_z}
; Wait for Build Plate Heatup:                  material_bed_temp_wait = {material_bed_temp_wait}
; Wait for Nozzle Heatup:                       material_print_temp_wait = {material_print_temp_wait}
; X Endstop in Positive Direction:              machine_endstop_positive_direction_x = {machine_endstop_positive_direction_x}
; Y Endstop in Positive Direction:              machine_endstop_positive_direction_y = {machine_endstop_positive_direction_y}
; Z Endstop in Positive Direction:              machine_endstop_positive_direction_z = {machine_endstop_positive_direction_z}

;; Command Line Settings
; Center Object:                                center_object = {center_object}
; Mesh Position X:                              mesh_position_x = {mesh_position_x}
; Mesh Position Y:                              mesh_position_y = {mesh_position_y}
; Mesh Position Z:                              mesh_position_z = {mesh_position_z}
; Mesh Rotation Matrix:                         mesh_rotation_matrix = {mesh_rotation_matrix}


;; End Cura Print Profile Settings
